/control/verbose
/process/em/verbose 0
/process/had/verbose 0
/tracking/verbose 2

/geometry/source detector.tg
/run/initialize

/vis/open
/vis/drawVolume
/vis/scene/add/axes
/vis/scene/add/gps

/tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/vis/viewer/zoom 0.5
/vis/viewer/refresh

/gps/position -35 0 0 cm
/gps/direction 1 0 0

/gps/particle alpha
/gps/energy 1 keV
/run/beamOn 10
/vis/viewer/refresh

/gps/particle e-
/gps/energy 1 MeV
/run/beamOn 10
/vis/viewer/refresh

/gps/particle gamma
/gps/energy 1 GeV
/run/beamOn 10
/vis/viewer/refresh

/gps/particle neutron
/gps/energy 1 MeV
/run/beamOn 10
/vis/viewer/refresh